name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'ga'
          
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet run --project ./tests/IsoTests.Tests --no-build -- --coverage --coverage-output-format cobertura --coverage-output ./coveragereport/coverage.cobertura.xml

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.16
        with:
          reports: cobertura.xml
          targetdir: coveragereport