name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iso_test_db

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'ga'
          
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        env:
          ConnectionStrings__Default: "Host=localhost;Port=5432;Database=${{ env.POSTGRES_DB }};Username=postgres;Password=${{ env.POSTGRES_PASSWORD }}"
        run: dotnet run --project ./tests/IsoTests.Tests --no-build -- --coverage --coverage-output-format cobertura --coverage-output ./coverage.cobertura.xml

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.16
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: coveragereport